# Used in HTML templates and titles
SiteTitle="ğŸŸflounder"
RootDomain="localhost"
FilesDirectory="./files"
# handles templates and static files
# everything in the static subfolder will be served at root
TemplatesDirectory="./templates"
DBFile="./flounder.db"

# Log file
